name: Deploy Node.js App to Azure Web App - estore

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        working-directory: backend
        run: npm install

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1E13D08C9D1A434B906F42C3FC875D77 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_FC51A850E68E4C4AAD37591A345E58F7 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8804C48550D04448B93F5F37B42A6DA4 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: estore
          slot-name: Production
          package: backend
